### ISSUE TITLE
Sculpt Tools not showing up after install

### ISSUE THREAD

**Issue by bjonesrock** [anfeo/Blender-Sculpt-Tools#1]
Hi I'm really excited to use your plugin. I want to use it to create Sprues for 3D printing jewelry.

I just installed your plugin on Blender 2.8 and I'm not seeing it show up in the add on list or in the Blender Layout tab header.

I installed it by opening up Blender Preferences>Add Ons
And then I clicked the Install Add On button and selected the ZIP file I downloaded from GitHub
A message in the bottom right is blue and says that it installed it.

I confirmed the files got installed in the following folder:
C:\Users\bjones\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Blender-Sculpt-Tools-master

I tried restarting Blender but that didn't help either. Any ideas what I'm doing wrong?

![Screenshot (1162)](https://user-images.githubusercontent.com/19981215/88465360-6565bc00-ce90-11ea-9b00-bb3c9bcc4b1a.png)

![Screenshot (1161)](https://user-images.githubusercontent.com/19981215/88465361-67c81600-ce90-11ea-8417-9ddee4750caa.png)

**Comment by Radivarig** [comment]
I can confirm this in Blender 2.90

**Comment by anfeo** [comment]
It is a Blender "bug" from github export.
You need to unzip the file and select for installation the .py file.

**Comment by bjonesrock** [comment]
Sweet that fixed it! 

For anyone else trying to install this plugin:

You have to enable the plugin in preferences and then go into the modeling tab and right click anything in the modeling menu and click Header > Show Tool Settings
![Screenshot (27)](https://user-images.githubusercontent.com/19981215/94151289-39db5f80-fe48-11ea-9348-e7940a1a6ad0.png)


It'll then show up for you on the top right of the screen

![Screenshot (28)](https://user-images.githubusercontent.com/19981215/94151367-4f508980-fe48-11ea-8774-595f454a8115.png)
